### ISSUE TITLE
Missing link to deployed version

### ISSUE THREAD

**Issue by linusblom** [chas-academy/12-instagram-clone-ulmez#1]
Please provide link to deployed version in README.md

**Comment by ulmez** [comment]
I have now provided link to deployed version in README.md file.

**Comment by axelolsson** [comment]
@ulmez Remember that you can close issues when you push commit messages to github. Just add the id of the issue like this in your commit message:

"Add deployed app to README.md Closes #1" <--- That would've closed this issue automagically!
